link:
  protocol: udp
  target: 192.168.137.255:5005
gamepad: Xbox360
mappings:
  axis:
    "LEFT-X":
      channel: rc4
      mode: passthrough
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 7
    "LEFT-Y":
      channel: rc3
      mode: passthrough
      weight: 100
      min: 100
      max: -100
      center: 0
      deadband: 7
    "RIGHT-X":
      channel: rc1
      mode: passthrough
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 7
    "RIGHT-Y":
      channel: rc2
      mode: passthrough
      weight: 100
      min: 100
      max: -100
      center: 0
      deadband: 7
    "6": # D-PAD
      channel: rc5
      mode: passthrough
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 0
    "7": # D-PAD
      channel: rc6
      mode: passthrough
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 0
    "LT":
      channel: rc7
      mode: passthrough
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 0
    "RT":
      channel: rc8
      mode: passthrough
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 0
  button:
    "A":
      channel: rc9
      mode: momentary
      pressed: 100
      released: -100
    "B":
      channel: rc10
      mode: momentary
      pressed: 100
      released: -100
    "X":
      channel: rc11
      mode: momentary
      pressed: 100
      released: -100
    "Y":
      channel: rc12
      mode: momentary
      pressed: 100
      released: -100
    "LB":
      channel: rc13
      mode: momentary
      pressed: 100
      released: -100
    "RB":
      channel: rc14
      mode: momentary
      pressed: 100
      released: -100
    "BACK":
      channel: rc15
      mode: momentary
      pressed: 100
      released: -100
    "START":
      channel: rc16
      mode: momentary
      pressed: 100
      released: -100
